// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOqB9UOAaaEKZ5-uMZLtVR8iEJJHLaKc',
    appId: '1:121106493217:web:7a4cca225accda5a3f9860',
    messagingSenderId: '121106493217',
    projectId: 'notepad-weather',
    authDomain: 'notepad-weather.firebaseapp.com',
    storageBucket: 'notepad-weather.appspot.com',
    measurementId: 'G-0JG82V1W0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVTEGMzeEiH6Wq55HSa_kz-vVLwDw-1Q',
    appId: '1:121106493217:android:55e46186047097613f9860',
    messagingSenderId: '121106493217',
    projectId: 'notepad-weather',
    storageBucket: 'notepad-weather.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw5_sVouTlvvkH9mC0gShIL_Pn0f8IknQ',
    appId: '1:121106493217:ios:74b03fbe5538cd483f9860',
    messagingSenderId: '121106493217',
    projectId: 'notepad-weather',
    storageBucket: 'notepad-weather.appspot.com',
    iosClientId: '121106493217-uutn1n8o4l9bul20i4kuott3one9ntdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepadWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw5_sVouTlvvkH9mC0gShIL_Pn0f8IknQ',
    appId: '1:121106493217:ios:9e32a0207e887d613f9860',
    messagingSenderId: '121106493217',
    projectId: 'notepad-weather',
    storageBucket: 'notepad-weather.appspot.com',
    iosClientId: '121106493217-8cojobaklnd49css0qnpdp3pqc3kv99n.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepadWeather.RunnerTests',
  );
}
